/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Modele_bdd.ConnectPatient;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.util.calendar.BaseCalendar;
import java.text.*;//etat d'impression
import javax.print.*;//etat d'impression
import javax.swing.JTable;

/**
 *
 * @author Acer
 */
public class Admission extends javax.swing.JFrame {

    ConnectPatient cp = new ConnectPatient();
    public ResultSet rs;
    public PreparedStatement ps;
    DefaultTableModel dtm = new DefaultTableModel();

    public Admission() {
        initComponents();
        setLocationRelativeTo(this);
       
        date();
        tdateen.setEditable(false);
        da.setEditable(false);
        th.setEditable(false);
        
        

    }
    
   
    public void afficher(int ls){
        
        tnumad.setText(tablep.getValueAt(ls, 0).toString());
        tnom.setText(tablep.getValueAt(ls, 1).toString());
        tprenom.setText(tablep.getValueAt(ls, 2).toString());
        cservice.setSelectedItem(tablep.getValueAt(ls, 3));
    }
    public void actualiser(){
        try {
            dtm.setRowCount(0);
            dtm.setColumnCount(0);
            
            cp.rs = cp.ps.executeQuery("select * from patient");//actualisation
            
            dtm.addColumn("N° d'admission");
            dtm.addColumn("Nom");
            dtm.addColumn("Prenom");
            dtm.addColumn("Service");

            while (cp.rs.next()) {
                dtm.addRow(new Object[]{cp.rs.getObject("NumAdmission"),
                    cp.rs.getObject("Nom"),
                    cp.rs.getObject("Prenom"),
                    cp.rs.getObject("Service")});

            }
            tablep.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(Admission.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    
    public void renitialiser(){
        tnumad.setText(null);
        tnom.setText(null);
        tprenom.setText(null);
        csexe.setSelectedItem("Homme");
        cservice.setSelectedItem("PNEUMO-PHTISIO");
        cgs.setSelectedItem(null);
       // tdateen.setText(null);
        th.setText(null);
        //tdatenaiss.setText(null);
        tlieunaiss.setSelectedItem("06 Bejaia");
        tprenomp.setText(null);
        tnomm.setText(null);
        tprenomm.setText(null);
        tadresse.setText(null);
        tsituation.setSelectedItem("Mariée");
        tnomepoux.setText(null);
        tnat.setText(null);
        tpro.setText(null);
        tnumtel.setText(null);
    }
    
    
     public void date(){
        Date d=new Date();
        SimpleDateFormat a = new SimpleDateFormat("dd/MM/yyyy");
        tdateen.setText(a.format(d));
        da.setText(a.format(d));
        SimpleDateFormat k = new SimpleDateFormat("HH : mm");
        th.setText(k.format(d));
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tnumad = new javax.swing.JTextField();
        tnom = new javax.swing.JTextField();
        tprenom = new javax.swing.JTextField();
        csexe = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cservice = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tprenomp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tnomm = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tprenomm = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tadresse = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tsituation = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        tnomepoux = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tpro = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tnumtel = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cgs = new javax.swing.JComboBox<>();
        tlieunaiss = new javax.swing.JComboBox<>();
        tnat = new javax.swing.JTextField();
        tdatenaiss = new com.toedter.calendar.JDateChooser();
        th = new javax.swing.JFormattedTextField();
        tdateen = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        bafficher = new javax.swing.JButton();
        bajouter = new javax.swing.JButton();
        bmodifier = new javax.swing.JButton();
        bactualiser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablep = new javax.swing.JTable();
        brecherche = new javax.swing.JButton();
        trecherche = new javax.swing.JTextField();
        da = new javax.swing.JFormattedTextField();
        lfermé = new javax.swing.JLabel();
        lfond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("       Admission");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 180, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Veuillez renseignre les champs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(0, 51, 153))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("N° d'admission:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Nom:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Prenom:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Sexe:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        tnumad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnumadActionPerformed(evt);
            }
        });
        tnumad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnumadKeyTyped(evt);
            }
        });
        jPanel1.add(tnumad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 110, -1));

        tnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnomActionPerformed(evt);
            }
        });
        tnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnomKeyTyped(evt);
            }
        });
        jPanel1.add(tnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 120, 20));

        tprenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tprenomActionPerformed(evt);
            }
        });
        tprenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tprenomKeyTyped(evt);
            }
        });
        jPanel1.add(tprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 130, -1));

        csexe.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        csexe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Homme", "Femme" }));
        csexe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csexeActionPerformed(evt);
            }
        });
        jPanel1.add(csexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Service:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        cservice.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cservice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PNEUMO-PHTISIO", "PSYCHIATRIE", "MAXILLO FACIALE", "ORL", "OPHTALMOLOGIE", "NEPHROLOGIE", "INFECTIOLOGIE", "HEMATOLOGIE", " " }));
        cservice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cserviceActionPerformed(evt);
            }
        });
        jPanel1.add(cservice, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Date d'entrée:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Heure d'entée:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Date de naissance:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Lieu de naissance:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Prenom du pere:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        tprenomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tprenompActionPerformed(evt);
            }
        });
        tprenomp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tprenompKeyTyped(evt);
            }
        });
        jPanel1.add(tprenomp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 100, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Nom de la mére:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        tnomm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnommActionPerformed(evt);
            }
        });
        tnomm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnommKeyTyped(evt);
            }
        });
        jPanel1.add(tnomm, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 110, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Prenom de la mére:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        tprenomm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tprenommActionPerformed(evt);
            }
        });
        tprenomm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tprenommKeyTyped(evt);
            }
        });
        jPanel1.add(tprenomm, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 110, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Adresse:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        tadresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tadresseActionPerformed(evt);
            }
        });
        jPanel1.add(tadresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 150, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Situation familiale:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        tsituation.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tsituation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marié(e)", "Celibataire", "Veuf(ve)" }));
        tsituation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsituationActionPerformed(evt);
            }
        });
        jPanel1.add(tsituation, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 80, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Nom de l'époux(se):");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, -1));

        tnomepoux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnomepouxActionPerformed(evt);
            }
        });
        tnomepoux.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnomepouxKeyTyped(evt);
            }
        });
        jPanel1.add(tnomepoux, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 110, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Nationnalité:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 20));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("Profession:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        tpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tproActionPerformed(evt);
            }
        });
        tpro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tproKeyTyped(evt);
            }
        });
        jPanel1.add(tpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 110, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setText("N° téléphone:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, 20));

        tnumtel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnumtelActionPerformed(evt);
            }
        });
        tnumtel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnumtelKeyTyped(evt);
            }
        });
        jPanel1.add(tnumtel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 110, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setText("Groupe sanguin:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        cgs.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cgs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "B+", "AB+", "O+", "A-", "B-", "AB-", "O-", " " }));
        jPanel1.add(cgs, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 100, -1));

        tlieunaiss.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tlieunaiss.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01  Adrar\t", "02  Chlef", "03  Laghouat", "04  Oum El Bouaghi", "05  Batna", "06  Béjaïa", "07  Biskra", "08  Béchar", "09  Blida\t", "10  Bouira\t", "11  Tamanrasset\t\t", "12  Tébessa\t ", "13  Tlemcen\t", "14  Tiaret\t", "15  Tizi Ouzou\t", "16  Alger\t", "17  Djelfa\t", "18  Jijel\t", "19  Sétif", "20  Saïda", "21  Skikda", "22  Sidi Bel Abbès", "23  Annaba", "24  Guelma\t", "25  Constantine\t", "26  Médéa", "27  Mostaganem\t", "28  M’Sila\t", "29  Mascara\t", "30  Ouargla\t", "31  Oran\t", "32  El Bayadh\t", "33  Illizi", "34  Bordj Bou Arreridj\t", "35  Boumerdès", "36  El Tarf", "37  Tindouf\t", "38  Tissemsilt", "39  El Oued\t", "40  Khenchela\t", "41  Souk Ahras", "42  Tipaza", "43  Mila", "44  Defla\t", "45  Naâma", "46  Aïn Témouchent", "47  Ghardaia\t", "48   Relizane" }));
        tlieunaiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlieunaissActionPerformed(evt);
            }
        });
        jPanel1.add(tlieunaiss, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 120, -1));

        tnat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnatKeyTyped(evt);
            }
        });
        jPanel1.add(tnat, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 120, -1));
        jPanel1.add(tdatenaiss, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 130, -1));

        th.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        th.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        th.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thActionPerformed(evt);
            }
        });
        jPanel1.add(th, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 140, -1));

        try {
            tdateen.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tdateen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tdateen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdateenActionPerformed(evt);
            }
        });
        jPanel1.add(tdateen, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 680, 290));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("Date:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        bafficher.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bafficher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IhmImage/Ouvrir.png"))); // NOI18N
        bafficher.setText("Afficher");
        bafficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bafficherActionPerformed(evt);
            }
        });
        getContentPane().add(bafficher, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 120, 40));

        bajouter.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IhmImage/Ajouter.png"))); // NOI18N
        bajouter.setText("Ajouter");
        bajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajouterActionPerformed(evt);
            }
        });
        getContentPane().add(bajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 120, 40));

        bmodifier.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bmodifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IhmImage/modifier.png"))); // NOI18N
        bmodifier.setText("Modifier");
        bmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodifierActionPerformed(evt);
            }
        });
        getContentPane().add(bmodifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 130, 40));

        bactualiser.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bactualiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IhmImage/actualiser.PNG"))); // NOI18N
        bactualiser.setText("Actualiser");
        bactualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bactualiserActionPerformed(evt);
            }
        });
        getContentPane().add(bactualiser, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 130, 40));

        tablep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablepMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablep);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 720, 90));

        brecherche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IhmImage/rechercher.png"))); // NOI18N
        brecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brechercheActionPerformed(evt);
            }
        });
        getContentPane().add(brecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));
        getContentPane().add(trecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 110, 20));

        try {
            da.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        da.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(da, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 140, -1));

        lfermé.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IhmImage/Fermer.png"))); // NOI18N
        lfermé.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lferméMouseClicked(evt);
            }
        });
        getContentPane().add(lfermé, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 30, 30));

        lfond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IhmImage/far.jpg"))); // NOI18N
        getContentPane().add(lfond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void tnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnomActionPerformed
     
       
    }//GEN-LAST:event_tnomActionPerformed

    private void tprenompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tprenompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tprenompActionPerformed

    private void tadresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tadresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tadresseActionPerformed

    private void tnomepouxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnomepouxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnomepouxActionPerformed

    private void tprenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tprenomActionPerformed

    }//GEN-LAST:event_tprenomActionPerformed

    private void tnumtelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnumtelActionPerformed
      /*  try {
            int ent=Integer.parseInt(tnumtel.getText().toString());
        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "Ce n'est pas un entier");
        }*/
        
    }//GEN-LAST:event_tnumtelActionPerformed

    private void tnommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnommActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnommActionPerformed

    private void tlieunaissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlieunaissActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlieunaissActionPerformed

    private void bajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajouterActionPerformed

        try {
            //le 'c' de la classe connectPatient

            ps = cp.c.connectbd().prepareStatement("insert into patient (NumAdmission,Nom,Prenom,Sexe,Service,GSanguin,DateEntree,HeureEntree,DateNaiss,LieuNaiss,PrenomPere,NomMere,PrenomMere,Adresse,SitFamiliale,NomEpoux,Nationnalité,Profession,NumTel) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1, tnumad.getText());
            ps.setString(2, tnom.getText());
            ps.setString(3, tprenom.getText());
            ps.setString(4, csexe.getSelectedItem().toString());
            ps.setString(5, cservice.getSelectedItem().toString());
            ps.setString(6, cgs.getSelectedItem().toString());
            ps.setString(7, tdateen.getText());
            ps.setString(8, th.getText());
            ps.setString(9, tdatenaiss.getDateFormatString());
            ps.setString(10, tlieunaiss.getSelectedItem().toString());

            ps.setString(11, tprenomp.getText());
            ps.setString(12, tnomm.getText());
            ps.setString(13, tprenomm.getText());
            ps.setString(14, tadresse.getText());
            ps.setString(15, tsituation.getSelectedItem().toString());
            ps.setString(16, tnomepoux.getText());
            ps.setString(17, tnat.getText());
            ps.setString(18, tpro.getText());
            ps.setString(19, tnumtel.getText());

            ps.execute();
            JOptionPane.showMessageDialog(this, "Ajout avec succés");
            renitialiser();
            actualiser();
            tnumad.requestFocus();

        } catch (SQLException ex) {
            Logger.getLogger(Admission.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Echec de l'ajout " + ex.getMessage());
        }
    }//GEN-LAST:event_bajouterActionPerformed

    private void tproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tproActionPerformed

    private void tnumadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnumadActionPerformed
      
    }//GEN-LAST:event_tnumadActionPerformed

    private void csexeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csexeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_csexeActionPerformed

    private void cserviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cserviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cserviceActionPerformed

    private void tprenommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tprenommActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tprenommActionPerformed

    private void tsituationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsituationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsituationActionPerformed

    private void bmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodifierActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment modifier?", "confirmation modification", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

            try {
                ps = cp.c.connectbd().prepareStatement("update patient set NumAdmission =?, Nom=?, Prenom=?, Sexe=? , Service=?  ,DateEntree=  ?,HeureEntree= ? ,DateNaiss= ? ,LieuNaiss= ? ,PrenomPere= ? ,NomMere= ? ,PrenomMere= ? ,Adresse= ? ,SitFamiliale=  ? ,NomEpoux= ? ,Nationnalité= ? ,Profession= ? ,NumTel= ? ,GSanguin=  ? ");

                ps.setString(1, tnumad.getText());
                ps.setString(2, tnom.getText());
                ps.setString(3, tprenom.getText());
                ps.setString(4, csexe.getSelectedItem().toString());
                ps.setString(5, cservice.getSelectedItem().toString());
                ps.setString(6, cgs.getSelectedItem().toString());
                ps.setString(7, tdateen.getText());
                ps.setString(8, th.getText());
                ps.setString(9, tdatenaiss.getDateFormatString());
                ps.setString(10, tlieunaiss.getSelectedItem().toString());

                ps.setString(11, tprenomp.getText());
                ps.setString(12, tnomm.getText());
                ps.setString(13, tprenomm.getText());
                ps.setString(14, tadresse.getText());
                ps.setString(15, tsituation.getSelectedItem().toString());
                ps.setString(16, tnomepoux.getText());
                ps.setString(17, tnat.getText());
                ps.setString(18, tpro.getText());
                ps.setString(19, tnumtel.getText());

                ps.execute();
                JOptionPane.showMessageDialog(this, "Modification avec succés");
            } catch (SQLException ex) {
                Logger.getLogger(Admission.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Echec de modification  "+ex.getMessage());
            }

        }

    }//GEN-LAST:event_bmodifierActionPerformed

    private void bafficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bafficherActionPerformed

        try {
            dtm.setRowCount(0);
            dtm.setColumnCount(0);

            cp.rs = cp.ps.executeQuery("select * from patient");//actualisation

            dtm.addColumn("N° d'admission");
            dtm.addColumn("Nom");
            dtm.addColumn("Prenom");
            dtm.addColumn("Service");

            while (cp.rs.next()) {
                dtm.addRow(new Object[]{cp.rs.getObject("NumAdmission"),
                    cp.rs.getObject("Nom"),
                    cp.rs.getObject("Prenom"),
                    cp.rs.getObject("Service")});

            }
            tablep.setModel(dtm);

        } catch (SQLException ex) {
            Logger.getLogger(Admission.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_bafficherActionPerformed

    private void tablepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablepMouseClicked
        afficher(tablep.getSelectedRow());
    }//GEN-LAST:event_tablepMouseClicked

    private void bactualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bactualiserActionPerformed
        actualiser();
        
    }//GEN-LAST:event_bactualiserActionPerformed

    private void brechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brechercheActionPerformed
       dtm.setRowCount(0);
       
        try {
            ps=cp.c.connectbd().prepareStatement("select from patient where Nom = ?");
            ps.setString(1, tnom.getText());
            cp.rs=ps.executeQuery();
            
            
            
            while (cp.rs.next()) {  
                dtm.addRow(new Object[]{cp.rs.getObject("NumAdmission"),cp.rs.getObject("Nom"),cp.rs.getObject("Prenom"),cp.rs.getObject("Service")
                });
            
        }
            if (dtm.getRowCount() != 0) {
                afficher(0);
                JOptionPane.showMessageDialog(this, "patient trouvé");
                
            } else {
                JOptionPane.showMessageDialog(this, "patient n'existe pas");
            }
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Admission.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_brechercheActionPerformed

    private void tnumadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnumadKeyTyped
         char car= evt.getKeyChar();
        if((car<'0' || car>'9' ) && tnumad.getText().contains(".")
            && (car!=(char)KeyEvent.VK_BACK_SPACE))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"seulment numero","validation  "
                ,JOptionPane.INFORMATION_MESSAGE);
        } else if
        ((car<'0' ||car>'9')&&(car!='.')
            &&(car!=(char)KeyEvent.VK_BACK_SPACE)){
            evt.consume();
            JOptionPane.showMessageDialog(null,"SVP entrer seulement des numero","message de confirmation"
                ,JOptionPane.INFORMATION_MESSAGE); }


    }//GEN-LAST:event_tnumadKeyTyped

    private void tnumtelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnumtelKeyTyped
        
         char car= evt.getKeyChar();
        if((car<'0' || car>'9' ) && tnumtel.getText().contains(".")
            && (car!=(char)KeyEvent.VK_BACK_SPACE))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"seulment numero","validation  "
                ,JOptionPane.INFORMATION_MESSAGE);
        } else if
        ((car<'0' ||car>'9')&&(car!='.')
            &&(car!=(char)KeyEvent.VK_BACK_SPACE)){
            evt.consume();
            JOptionPane.showMessageDialog(null,"SVP entrer seulement des numero","message de confirmation  "
                ,JOptionPane.INFORMATION_MESSAGE); }


    }//GEN-LAST:event_tnumtelKeyTyped

    private void tnomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnomKeyTyped
        char car= evt.getKeyChar();
        if((car<'a' || car>'z' ) && (car<'A' || car>'Z' )
            && (car!=(char)KeyEvent.VK_BACK_SPACE)&& (car!=(char)KeyEvent.VK_SPACE))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"seulement les lettre qui sont accepter ","validat d'accepter des lettre"
                ,JOptionPane.INFORMATION_MESSAGE);
    }  

    }//GEN-LAST:event_tnomKeyTyped

    private void tprenomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tprenomKeyTyped
       char car= evt.getKeyChar();
        if((car<'a' || car>'z' ) && (car<'A' || car>'Z' )
            && (car!=(char)KeyEvent.VK_BACK_SPACE)&& (car!=(char)KeyEvent.VK_SPACE))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"seulement les lettre qui sont accepter ","validat d'accepter des lettre"
                ,JOptionPane.INFORMATION_MESSAGE);
    }  

    }//GEN-LAST:event_tprenomKeyTyped

    private void tprenompKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tprenompKeyTyped
       char car= evt.getKeyChar();
        if((car<'a' || car>'z' ) && (car<'A' || car>'Z' )
            && (car!=(char)KeyEvent.VK_BACK_SPACE)&& (car!=(char)KeyEvent.VK_SPACE))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"seulement les lettre qui sont accepter ","validat d'accepter des lettre"
                ,JOptionPane.INFORMATION_MESSAGE);
    }  

    }//GEN-LAST:event_tprenompKeyTyped

    private void tnommKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnommKeyTyped
      char car= evt.getKeyChar();
        if((car<'a' || car>'z' ) && (car<'A' || car>'Z' )
            && (car!=(char)KeyEvent.VK_BACK_SPACE)&& (car!=(char)KeyEvent.VK_SPACE))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"seulement les lettre qui sont accepter ","validat d'accepter des lettre"
                ,JOptionPane.INFORMATION_MESSAGE);
    }  

    }//GEN-LAST:event_tnommKeyTyped

    private void tprenommKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tprenommKeyTyped
    char car= evt.getKeyChar();
        if((car<'a' || car>'z' ) && (car<'A' || car>'Z' )
            && (car!=(char)KeyEvent.VK_BACK_SPACE)&& (car!=(char)KeyEvent.VK_SPACE))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"seulement les lettre qui sont accepter ","validat d'accepter des lettre"
                ,JOptionPane.INFORMATION_MESSAGE);
    }  

    }//GEN-LAST:event_tprenommKeyTyped

    private void tnomepouxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnomepouxKeyTyped
     char car= evt.getKeyChar();
        if((car<'a' || car>'z' ) && (car<'A' || car>'Z' )
            && (car!=(char)KeyEvent.VK_BACK_SPACE)&& (car!=(char)KeyEvent.VK_SPACE))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"seulement les lettre qui sont accepter ","validat d'accepter des lettre"
                ,JOptionPane.INFORMATION_MESSAGE);
    }  

    }//GEN-LAST:event_tnomepouxKeyTyped

    private void tnatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnatKeyTyped
      char car= evt.getKeyChar();
        if((car<'a' || car>'z' ) && (car<'A' || car>'Z' )
            && (car!=(char)KeyEvent.VK_BACK_SPACE)&& (car!=(char)KeyEvent.VK_SPACE))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"seulement les lettre qui sont accepter ","validat d'accepter des lettre"
                ,JOptionPane.INFORMATION_MESSAGE);
    }  

    }//GEN-LAST:event_tnatKeyTyped

    private void tproKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tproKeyTyped
    char car= evt.getKeyChar();
        if((car<'a' || car>'z' ) && (car<'A' || car>'Z' )
            && (car!=(char)KeyEvent.VK_BACK_SPACE)&& (car!=(char)KeyEvent.VK_SPACE))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"seulement les lettre qui sont accepter ","validat d'accepter des lettre"
                ,JOptionPane.INFORMATION_MESSAGE);
    }  

    }//GEN-LAST:event_tproKeyTyped

    private void thActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thActionPerformed

    private void tdateenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdateenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdateenActionPerformed

    private void lferméMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lferméMouseClicked
       dispose();
    }//GEN-LAST:event_lferméMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admission().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bactualiser;
    private javax.swing.JButton bafficher;
    private javax.swing.JButton bajouter;
    private javax.swing.JButton bmodifier;
    private javax.swing.JButton brecherche;
    private javax.swing.JComboBox<String> cgs;
    private javax.swing.JComboBox<String> cservice;
    private javax.swing.JComboBox<String> csexe;
    private javax.swing.JFormattedTextField da;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lfermé;
    private javax.swing.JLabel lfond;
    private javax.swing.JTable tablep;
    private javax.swing.JTextField tadresse;
    private javax.swing.JFormattedTextField tdateen;
    private com.toedter.calendar.JDateChooser tdatenaiss;
    private javax.swing.JFormattedTextField th;
    private javax.swing.JComboBox<String> tlieunaiss;
    private javax.swing.JTextField tnat;
    private javax.swing.JTextField tnom;
    private javax.swing.JTextField tnomepoux;
    private javax.swing.JTextField tnomm;
    private javax.swing.JTextField tnumad;
    private javax.swing.JTextField tnumtel;
    private javax.swing.JTextField tprenom;
    private javax.swing.JTextField tprenomm;
    private javax.swing.JTextField tprenomp;
    private javax.swing.JTextField tpro;
    private javax.swing.JTextField trecherche;
    private javax.swing.JComboBox<String> tsituation;
    // End of variables declaration//GEN-END:variables
}
