/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Modele_bdd.ConnectPersonnel;
import Modele_bdd.Connecter;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer
 */
public class Administrateur extends javax.swing.JFrame {

    
    public Connecter cn = new Connecter();
   // public ConnectPersonnel cpr=new ConnectPersonnel();
    public ResultSet rs;
    public Statement st;
    DefaultTableModel dtm =new DefaultTableModel();

    public Administrateur() {
        initComponents();
        setLocationRelativeTo(this);

        try {
            st=cn.connectbd().createStatement();
            rs=st.executeQuery("select Matricule,NomUtilisteur,MotDePasse,Nom,Prenom,Role from utilisateur");
            
            dtm.addColumn("Matricule");
            dtm.addColumn("nom d'utilisateur");
            dtm.addColumn("Mot de passe");
            dtm.addColumn("Nom");
            dtm.addColumn("Prenom");
            dtm.addColumn("Role");
            
            while (rs.next()) { 
               dtm.addRow(new Object[]{
                   rs.getObject("Matricule"),
                   rs.getObject("NomUtilisateur"),
                   rs.getObject("MotDePasse"),
                   rs.getObject("Nom"),
                   rs.getObject("Prenom"),
                   rs.getObject("Role")
                   
               });
                
            }
            tableuser.setModel(dtm);
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Administrateur.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    public void renitialiser(){
        
        tmdp.setText(null);
        tnom.setText(null);
        tprenom.setText(null);
        nuser.setText(null);
        //tdaten.setText(null);
        crole.setSelectedItem("Administrateur");
    }
    
    
     public String matricule(String s) {

        String mat = null;

       mat= tnom.getText().substring(0, 3).toUpperCase() 
               +tprenom.getText().substring(0,2).toUpperCase()
              // +tdaten.getDateFormatString().substring(8)
               +s
               +tableuser.getRowCount() +1;
        return mat;
    }
    
    
    
    
    
    
              
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ltitre = new javax.swing.JLabel();
        tdate = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tnom = new javax.swing.JTextField();
        crole = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tmdp = new javax.swing.JPasswordField();
        tdaten = new com.toedter.calendar.JDateChooser();
        lmatricule = new javax.swing.JLabel();
        tprenom = new javax.swing.JTextField();
        nuser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        bajouter = new javax.swing.JButton();
        bmodifier = new javax.swing.JButton();
        bsupprimer = new javax.swing.JButton();
        brecherche = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableuser = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ltitre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ltitre.setText("      GESTION DES COMPTES UTILISATURS");
        getContentPane().add(ltitre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 390, 30));

        tdate.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Renseignez les champs:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N
        tdate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Nom:");
        tdate.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Prenom:");
        tdate.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Date de naissance:");
        tdate.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Role:");
        tdate.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        tnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnomKeyTyped(evt);
            }
        });
        tdate.add(tnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 160, -1));

        crole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrateur", "Agent de saisie", "Chef service", "Medecin", " " }));
        crole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                croleActionPerformed(evt);
            }
        });
        tdate.add(crole, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 160, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Matricule:");
        tdate.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Mot de passe:");
        tdate.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        tmdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmdpActionPerformed(evt);
            }
        });
        tdate.add(tmdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 160, -1));
        tdate.add(tdaten, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 160, -1));

        lmatricule.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lmatricule.setText("..................................................");
        tdate.add(lmatricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 160, -1));
        tdate.add(tprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 160, -1));

        nuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuserActionPerformed(evt);
            }
        });
        tdate.add(nuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 160, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Nom d'utilisateur:");
        tdate.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, -1));

        getContentPane().add(tdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 400, 250));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 110, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mise a jour", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bajouter.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IhmImage/Ajouter.png"))); // NOI18N
        bajouter.setText("Ajouter");
        bajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajouterActionPerformed(evt);
            }
        });
        jPanel2.add(bajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 120, -1));

        bmodifier.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bmodifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IhmImage/modifier.png"))); // NOI18N
        bmodifier.setText("Modifier");
        bmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodifierActionPerformed(evt);
            }
        });
        jPanel2.add(bmodifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 120, -1));

        bsupprimer.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bsupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IhmImage/Supprimer.png"))); // NOI18N
        bsupprimer.setText("Supprimer");
        jPanel2.add(bsupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 120, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 240, 230));

        brecherche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IhmImage/rechercher.png"))); // NOI18N
        getContentPane().add(brecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 40, 40));

        tableuser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableuser);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 620, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajouterActionPerformed
      try {
            st=cn.connectbd().createStatement();
            st.executeUpdate("insert into utilisateur (Matricule,NomUtilisateur,MotDePasse,Nom,Prenom,DateNaiss,Role) values ('"+lmatricule.getText()+"','"+ nuser.getText() +"','" + tmdp.getText()+ "','"+ tnom.getText()+"','"+  tprenom.getText() +"','"+  tdaten.getDateFormatString() + "','"+crole.getSelectedItem()+"')");
            JOptionPane.showMessageDialog(this, "Ajout avec succés");
           
            renitialiser();
        } catch (SQLException ex) {
        
            JOptionPane.showMessageDialog(this, " echec de l'ajout  "+ex.getMessage());
        }
        
     
    }//GEN-LAST:event_bajouterActionPerformed

    private void tmdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmdpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmdpActionPerformed

    private void croleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_croleActionPerformed
       
        if (crole.getSelectedItem().equals("Administrateur")) {
            
            lmatricule.setText(matricule("ADM"));
            
        } else {
            
            if (crole.getSelectedItem().equals("Agent de saisie")) {
                lmatricule.setText(matricule("AGS"));
                
            } else {
                if (crole.getSelectedItem().equals("Medecin")) {
                    lmatricule.setText(matricule("MED"));
                    
                } else {
                    lmatricule.setText(matricule("CHS"));
                }
            }
        }
    }//GEN-LAST:event_croleActionPerformed

    private void tnomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnomKeyTyped
      
          char car= evt.getKeyChar();
        if((car<'a' || car>'z' ) && (car<'A' || car>'Z' )
            && (car!=(char)KeyEvent.VK_BACK_SPACE)&& (car!=(char)KeyEvent.VK_SPACE))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"seulement les lettre qui sont accepter ","validat d'accepter des lettre"
                ,JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_tnomKeyTyped
/**/
    }
    private void bmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodifierActionPerformed
       
          if (JOptionPane.showConfirmDialog(this, "Voulez-vous vraimemnt modifier?", "confirmation modification", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
       
        try {
            st = cn.connectbd().createStatement();
            st.executeUpdate("update utilisateur set MotDePasse ='"+tmdp.getText()+
                    "', Nom='"+tnom.getText()+
                    "',Prenom='"+tprenom.getText()+
                    "',Role='"+crole.getSelectedItem()+
                    "' where Matricule='"+
                    tableuser.getValueAt(tableuser.getSelectedRow(), 0)+"'");
            JOptionPane.showMessageDialog(this, "modification avec succés");
            //actualiser();
            renitialiser();
            
        } catch (SQLException ex) {
            Logger.getLogger(Administrateur.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "erreur de modifiction");
        } }
        
        
          
    }//GEN-LAST:event_bmodifierActionPerformed

    private void nuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuserActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrateur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bajouter;
    private javax.swing.JButton bmodifier;
    private javax.swing.JButton brecherche;
    private javax.swing.JButton bsupprimer;
    private javax.swing.JComboBox<String> crole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lmatricule;
    private javax.swing.JLabel ltitre;
    private javax.swing.JTextField nuser;
    private javax.swing.JTable tableuser;
    private javax.swing.JPanel tdate;
    private com.toedter.calendar.JDateChooser tdaten;
    private javax.swing.JPasswordField tmdp;
    private javax.swing.JTextField tnom;
    private javax.swing.JTextField tprenom;
    // End of variables declaration//GEN-END:variables
}
