/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Modele_bdd.ConnectUtilisateur;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class Authentification extends javax.swing.JFrame {

    /**
     * Creates new form Authentification
     */
    public Authentification() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tuser = new javax.swing.JTextField();
        tmdp = new javax.swing.JPasswordField();
        bconnecter = new javax.swing.JButton();
        bannuler = new javax.swing.JButton();
        lfond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Veuillez renseigner les champs");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Nom d'utilisateur:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Mot de passe:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        jPanel1.add(tuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 150, 30));

        tmdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmdpActionPerformed(evt);
            }
        });
        jPanel1.add(tmdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 150, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 360, 250));

        bconnecter.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bconnecter.setText("se connecter");
        bconnecter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bconnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bconnecterActionPerformed(evt);
            }
        });
        getContentPane().add(bconnecter, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 120, 30));

        bannuler.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bannuler.setText("annuler");
        bannuler.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bannuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bannulerActionPerformed(evt);
            }
        });
        getContentPane().add(bannuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 100, 30));

        lfond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IhmImage/Authentification.jpg"))); // NOI18N
        getContentPane().add(lfond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bannulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bannulerActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bannulerActionPerformed

    private void bconnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bconnecterActionPerformed

        try {
            //   boolean tr = false;

            ConnectUtilisateur cu = new ConnectUtilisateur();

            while (cu.rs.next()) {

                if (cu.rs.getString("NomUtilisateur").equals(tuser.getText()) && cu.rs.getString("MotDePasse").equals(tmdp.getText())) {

                    if (cu.rs.getString("Role").equals("Agent de saisie")) {
                        Admission a = new Admission();
                        a.setVisible(true);

                    } else if (cu.rs.getString("Role").equals("Administrateur")) {
                        Administrateur ad = new Administrateur();
                        ad.setVisible(true);
                    } else 
                        if (cu.rs.getString("Role").equals("Medecin")) {
                            Medecin md = new Medecin();
                            md.setVisible(true);

                        }else 
                    

                    if (cu.rs.getString("Role").equals("Chef service")) {
                        Statistique ss = new Statistique();
                        ss.setVisible(true);

                    }

                } /*else {
                    JOptionPane.showMessageDialog(this, "Nom d'utilisateur ou mot de passe incorrecte!");
                    tuser.setText(null);
                    tmdp.setText(null);
                    tuser.requestFocus();
                }*/
            }

            /* if (tr == true) {
            
            Admission a = new Admission();
            a.setVisible(true);
            } else {
            JOptionPane.showMessageDialog(this, "nom d'utilisateur ou mot de passe incorrecte");
            tuser.setText(null);
            tmdp.setText(null);
            tuser.requestFocus();
            }*/
 /* } catch (SQLException ex) {
            Logger.getLogger(Authentification.class.getName()).log(Level.SEVERE, null, ex);
            }
            } catch (SQLException ex) {
            Logger.getLogger(Authentification.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            /*  try {
            
            while (cu.rs.next()) {
            if (cu.rs.getString("NomUtilisateur").equals(tuser.getText()) && cu.rs.getString("MotDePasse").equals(tmdp.getText())) {
            tr = true;
            break;
            }
            }
            if (tr == true) {
            Admission a = new Admission();
            a.setVisible(true);
            
            } else {
            JOptionPane.showMessageDialog(this, "nom d'utilisateur ou mot de passe incorrecte");
            tuser.setText(null);
            tmdp.setText(null);
            tuser.requestFocus();
            }
            } catch (SQLException ex) {
            Logger.getLogger(Authentification.class.getName()).log(Level.SEVERE, null, ex);
            }*/
 /* if (cformation.getSelectedItem().equals("Administrateur")) {
            
            try {
            
            while (cu.rs.next()) {
            if (cu.rs.getString("NomUtilisateur").equals(tuser.getText()) && cu.rs.getString("MotDePasse").equals(tmdp.getText())) {
            
            tr = true;
            break;
            }
            
            }
            if (tr == true) {
            Administrateur adm = new Administrateur();
            adm.setVisible(true);
            
            } else {
            JOptionPane.showMessageDialog(this, "nom d'utilisateur ou mot de passe incorrecte");
            tuser.setText(null);
            tmdp.setText(null);
            tuser.requestFocus();
            }
            } catch (SQLException ex) {
            Logger.getLogger(Authentification.class.getName()).log(Level.SEVERE, null, ex);
            }
            }*/
 /*  if (cformation.getSelectedItem().equals("Medecin")) {
            try {
            
            while (cu.rs.next()) {
            if (cu.rs.getString("NomUtilisateur").equals(tuser.getText()) && cu.rs.getString("MotDePasse").equals(tmdp.getText())) {
            
            //  String type = cu.rs.getString("type");
            
            /* if (type.equals("Medecin")) {
            Medecin m = new Medecin();
            m.setVisible(true);
            }
            System.out.println("medecin");
             */
 /* tr = true;
            break;
            }
            
            }
            if (tr == true) {
            Medecin m = new Medecin();
            m.setVisible(true);
            
            } else {
            JOptionPane.showMessageDialog(this, "nom d'utilisateur ou mot de passe incorrecte");
            }
            } catch (SQLException ex) {
            Logger.getLogger(Authentification.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            }*/
        } catch (SQLException ex) {
            Logger.getLogger(Authentification.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_bconnecterActionPerformed

    private void tmdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmdpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmdpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authentification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bannuler;
    private javax.swing.JButton bconnecter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lfond;
    private javax.swing.JPasswordField tmdp;
    private javax.swing.JTextField tuser;
    // End of variables declaration//GEN-END:variables
}
